# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_pg1_1 = QtWidgets.QGroupBox(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pg1_1.sizePolicy().hasHeightForWidth())
        self.groupBox_pg1_1.setSizePolicy(sizePolicy)
        self.groupBox_pg1_1.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_pg1_1.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_pg1_1.setObjectName("groupBox_pg1_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_pg1_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView_pg1_gp1_1 = QtWidgets.QListView(self.groupBox_pg1_1)
        self.listView_pg1_gp1_1.setObjectName("listView_pg1_gp1_1")
        self.verticalLayout.addWidget(self.listView_pg1_gp1_1)
        self.widget = QtWidgets.QWidget(self.groupBox_pg1_1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(202, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_pg1_gp1_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_pg1_gp1_1.setObjectName("pushButton_pg1_gp1_1")
        self.horizontalLayout_2.addWidget(self.pushButton_pg1_gp1_1)
        self.pushButton_pg1_gp1_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_pg1_gp1_2.setObjectName("pushButton_pg1_gp1_2")
        self.horizontalLayout_2.addWidget(self.pushButton_pg1_gp1_2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_pg1_1)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_pg1_gp1_1 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_pg1_gp1_1.setObjectName("lineEdit_pg1_gp1_1")
        self.horizontalLayout_3.addWidget(self.lineEdit_pg1_gp1_1)
        self.pushButton_pg1_gp1_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_pg1_gp1_3.setObjectName("pushButton_pg1_gp1_3")
        self.horizontalLayout_3.addWidget(self.pushButton_pg1_gp1_3)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout_6.addWidget(self.groupBox_pg1_1)
        self.groupBox_pg1_2 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_pg1_2.setTitle("")
        self.groupBox_pg1_2.setObjectName("groupBox_pg1_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_pg1_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_pg1_gp2_1 = QtWidgets.QTableView(self.groupBox_pg1_2)
        self.tableView_pg1_gp2_1.setObjectName("tableView_pg1_gp2_1")
        self.verticalLayout_3.addWidget(self.tableView_pg1_gp2_1)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_pg1_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_pg1_gp2_1 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_pg1_gp2_1.setObjectName("pushButton_pg1_gp2_1")
        self.horizontalLayout_4.addWidget(self.pushButton_pg1_gp2_1)
        self.pushButton_pg1_gp2_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_pg1_gp2_2.setObjectName("pushButton_pg1_gp2_2")
        self.horizontalLayout_4.addWidget(self.pushButton_pg1_gp2_2)
        self.pushButton_pg1_gp2_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_pg1_gp2_3.setObjectName("pushButton_pg1_gp2_3")
        self.horizontalLayout_4.addWidget(self.pushButton_pg1_gp2_3)
        self.pushButton_pg1_gp2_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_pg1_gp2_4.setObjectName("pushButton_pg1_gp2_4")
        self.horizontalLayout_4.addWidget(self.pushButton_pg1_gp2_4)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_pg1_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(189, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_pg1_gp2_1 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_pg1_gp2_1.setObjectName("lineEdit_pg1_gp2_1")
        self.horizontalLayout_5.addWidget(self.lineEdit_pg1_gp2_1)
        self.comboBox_pg1_gp2_1 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_pg1_gp2_1.setObjectName("comboBox_pg1_gp2_1")
        self.horizontalLayout_5.addWidget(self.comboBox_pg1_gp2_1)
        self.pushButton_pg1_gp2_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_pg1_gp2_5.setObjectName("pushButton_pg1_gp2_5")
        self.horizontalLayout_5.addWidget(self.pushButton_pg1_gp2_5)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout_6.addWidget(self.groupBox_pg1_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 23))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_mn1_1 = QtWidgets.QAction(MainWindow)
        self.action_mn1_1.setObjectName("action_mn1_1")
        self.action_mn1_2 = QtWidgets.QAction(MainWindow)
        self.action_mn1_2.setObjectName("action_mn1_2")
        self.action_mn2_1 = QtWidgets.QAction(MainWindow)
        self.action_mn2_1.setObjectName("action_mn2_1")
        self.action_mn2_2 = QtWidgets.QAction(MainWindow)
        self.action_mn2_2.setObjectName("action_mn2_2")
        self.menu_1.addAction(self.action_mn1_1)
        self.menu_1.addAction(self.action_mn1_2)
        self.menu_2.addAction(self.action_mn2_1)
        self.menu_2.addAction(self.action_mn2_2)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "产品管理系统主界面"))
        self.groupBox_pg1_1.setTitle(_translate("MainWindow", "产品表："))
        self.pushButton_pg1_gp1_1.setText(_translate("MainWindow", "删除"))
        self.pushButton_pg1_gp1_2.setText(_translate("MainWindow", "新建"))
        self.label_3.setText(_translate("MainWindow", "请输入关键字："))
        self.pushButton_pg1_gp1_3.setText(_translate("MainWindow", "查找"))
        self.pushButton_pg1_gp2_1.setText(_translate("MainWindow", "增加"))
        self.pushButton_pg1_gp2_2.setText(_translate("MainWindow", "删除"))
        self.pushButton_pg1_gp2_3.setText(_translate("MainWindow", "提交"))
        self.pushButton_pg1_gp2_4.setText(_translate("MainWindow", "取消"))
        self.label_4.setText(_translate("MainWindow", "请输入关键字："))
        self.pushButton_pg1_gp2_5.setText(_translate("MainWindow", "查找"))
        self.label.setText(_translate("MainWindow", "产品分析，带扩展"))
        self.label_2.setText(_translate("MainWindow", "欢迎来到产品大数据信息管理系统"))
        self.menu_1.setTitle(_translate("MainWindow", "账户"))
        self.menu_2.setTitle(_translate("MainWindow", "产品"))
        self.action_mn1_1.setText(_translate("MainWindow", "注销"))
        self.action_mn1_2.setText(_translate("MainWindow", "退出"))
        self.action_mn2_1.setText(_translate("MainWindow", "管理"))
        self.action_mn2_2.setText(_translate("MainWindow", "分析"))

