# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newproducttabledialogueUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewProductTableDialog(object):
    def setupUi(self, NewProductTableDialog):
        NewProductTableDialog.setObjectName("NewProductTableDialog")
        NewProductTableDialog.resize(478, 365)
        self.gridLayout_2 = QtWidgets.QGridLayout(NewProductTableDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(NewProductTableDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(NewProductTableDialog)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_2.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(NewProductTableDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView_1 = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_1.setObjectName("tableView_1")
        self.horizontalLayout_2.addWidget(self.tableView_1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 3, 2)
        self.groupBox = QtWidgets.QGroupBox(NewProductTableDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_3.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.widget = QtWidgets.QWidget(NewProductTableDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.gridLayout_2.addWidget(self.widget, 3, 2, 1, 1)

        self.retranslateUi(NewProductTableDialog)
        QtCore.QMetaObject.connectSlotsByName(NewProductTableDialog)

    def retranslateUi(self, NewProductTableDialog):
        _translate = QtCore.QCoreApplication.translate
        NewProductTableDialog.setWindowTitle(_translate("NewProductTableDialog", "新建产品表"))
        self.label.setText(_translate("NewProductTableDialog", "产品名称："))
        self.groupBox_2.setTitle(_translate("NewProductTableDialog", "产品属性："))
        self.groupBox.setTitle(_translate("NewProductTableDialog", "产品属性添加："))
        self.label_2.setText(_translate("NewProductTableDialog", "属性名称："))
        self.label_3.setText(_translate("NewProductTableDialog", "属性类型："))
        self.comboBox_1.setItemText(0, _translate("NewProductTableDialog", "int"))
        self.comboBox_1.setItemText(1, _translate("NewProductTableDialog", "float"))
        self.comboBox_1.setItemText(2, _translate("NewProductTableDialog", "char(30)"))
        self.comboBox_1.setItemText(3, _translate("NewProductTableDialog", "datetime"))
        self.comboBox_1.setItemText(4, _translate("NewProductTableDialog", "date"))
        self.pushButton_1.setText(_translate("NewProductTableDialog", "添加"))
        self.pushButton_2.setText(_translate("NewProductTableDialog", "删除"))
        self.pushButton_3.setText(_translate("NewProductTableDialog", "新建"))
        self.pushButton_4.setText(_translate("NewProductTableDialog", "取消"))

